spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maplegarage_appointments
    username: maplegarage
    password: maplepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
